# Generated by Django 6.0.3 on 2026-06-29 08:05

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyllabusEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField(help_text="The original text chunk")),
                (
                    "chunk_index",
                    models.IntegerField(
                        default=0, help_text="Position of this chunk in the document"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=384, help_text="384-dim embedding vector"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="syllabus.course",
                    ),
                ),
                (
                    "syllabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="syllabus.syllabusfile",
                    ),
                ),
            ],
            options={
                "ordering": ["syllabus", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["course"], name="syllabus_sy_course__f88584_idx"
                    )
                ],
            },
        ),
    ]
